name: Cleanup Workflow Runs

on:
  schedule:
    # Run cleanup weekly on Sundays at 2 AM
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Cleanup old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 30
        keep_minimum_runs: 10
